config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'

  resources :pictures

end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.create(picture_params)
    if @picture.save
      redirect_to pictures_path
    else
      render :new
    end
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update_attributes(picture_params)
      redirect_to pictures_path
    else
      redner :edit
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_path
  end

  private

  def picture_params
    params.require(:picture).permit(:artist, :title, :url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Photogur+</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "Add Photo", new_picture_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogurplus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  


  <%= yield %>

</body>
</html>

app/views/pictures/edit.html.erb
<h1>Edit a Photo</h1>

<%= form_for @picture do |f| %>
  <div class="form-group">
    <%= f.label :artist %>
    <%= f.text_field :artist, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/pictures/index.html.erb
  <% @pictures.each do |picture| %>
    <p><%= picture.title %> | <%= picture.artist %></p>
    <%= link_to image_tag(picture.url), "/pictures/#{picture.id}" %>
  <% end %>

app/views/pictures/new.html.erb
  <%= form_for @picture do |f| %>
    <div class="form-group">
      <%= f.label :artist %>
      <%= f.text_field :artist, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :url %>
      <%= f.text_field :url, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit "Save" %>
    </div>
  <% end %>

app/views/pictures/show.html.erb
<div class="container">
  <h1>A closer look</h1>

  <p><%= @picture.title %> | <%= @picture.artist %></p>
  <%= image_tag @picture.url %>

  <div class="container">
    <%= link_to "Back", pictures_path, class: "testtest" %>
    <%= link_to "Edit", edit_picture_path, class: "testtest" %>
    <%= link_to "Delete", @picture, method: :delete, data: {confirm: "Are you sure you want to delete this photo?" }, class: "testtest" %>
  </div>

</div>